1.3.1 Задание. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [3]:
import numpy as np
answer = np.zeros((8, 8), dtype = int)
answer[1::2, ::2] = answer[::2, 1::2] = 1
print(answer)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание. Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.

In [3]:
import numpy as np
answer = np.tile(np.arange(5), (5, 1))
print(answer)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание. Создать массив 3x3x3 со случайными значениями.

In [5]:
import numpy as np
answer = np.random.random((3, 3, 3))
print(answer)

[[[0.06440172 0.31733604 0.11727882]
  [0.39088577 0.59074059 0.67138923]
  [0.13481854 0.45248161 0.15814938]]

 [[0.15740817 0.17119414 0.72495737]
  [0.18775053 0.96238645 0.51124624]
  [0.15703368 0.10915794 0.25667583]]

 [[0.60134292 0.7775742  0.86176268]
  [0.16552889 0.94380343 0.1944866 ]
  [0.16776954 0.10683693 0.12555325]]]


1.3.4 Задание. Создать матрицу с 0 внутри, и 1 на границах. 

In [1]:
import numpy as np
core = np.zeros((6, 6), dtype=int)
answer = np.pad(core, pad_width=1, constant_values=1)  # добавляем рамку из 1
print(answer)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


1.3.5 Задание. Создайте массив и отсортируйте его по убыванию. 

In [8]:
import numpy as np
array = np.random.randint(1, 100 + 1, size = 10)
answer = np.sort(array)[::-1]
print(*answer)

95 92 92 90 74 72 52 43 29 22


1.3.6 Задание. Создайте матрицу, выведите ее форму, размер и размерность. 

In [3]:
import numpy as np
matrix = np.random.random((5,5))
print(f"Форма матрицы: {matrix.shape}")
print(f"Размер матрицы: {matrix.size}")
print(f"Размерность матрицы: {matrix.ndim}")

Форма матрицы: (5, 5)
Размер матрицы: 25
Размерность матрицы: 2


2.3.1 Задание. Найдите евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [10]:
import pandas as pd
import numpy as np

a = pd.Series([1, 2, 3, 4])
b = pd.Series([5, 6, 7, 8])
distance = np.sqrt(((a - b) ** 2).sum())

print(distance)


8.0


2.3.2 Задание. Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets).

In [19]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/airlines.csv'
df = pd.read_csv(url)

print(df.head(5))

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0


2.3.3 Задание. Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/airlines.csv"

# 2.2.5
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape # размер таблицы в виде (число строк, число столбцов)
dataframe.describe() # выдаёт основные статистические характеристики числовых столбцов

# 2.2.6
dataframe.iloc[1:4]

# 2.2.7
dataframe[dataframe['Flight'] > 2000].head(2)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

3.3.2 Задание. Загрузить фрейм данных по ссылке: 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования. 

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

min_max_scaler = MinMaxScaler() # для выполнения минимаксного преобразования
z_scaler = StandardScaler() # для выполнения z-стандартизации

# применяем минимаксное преобразование к признаку "sepal_length_cm"
# (масштабируем его значения в диапазон [0, 1])
df['sepal_length_cm'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

# применяем z-стандартизацию к признаку "sepal_width_cm"
# (преобразуем данные так, чтобы их среднее стало 0, а стандартное отклонение 1)
df['sepal_width_cm'] = z_scaler.fit_transform(df[['sepal_width_cm']])

print(df[['sepal_length_cm', 'sepal_width_cm']].head())

   sepal_length_cm  sepal_width_cm
0         0.222222        1.032057
1         0.166667       -0.124958
2         0.111111        0.337848
3         0.083333        0.106445
4         0.194444        1.263460
